# Generated by Django 5.2.15 on 2026-06-19 13:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Fecha de Eliminación')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('licencia', models.CharField(max_length=30, unique=True, verbose_name='N.° de Licencia')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_RUTA', 'En Ruta'), ('MANTENIMIENTO', 'No Disponible')], db_index=True, default='DISPONIBLE', max_length=20, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Conductor',
                'verbose_name_plural': 'Conductores',
                'db_table': 'conductores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Fecha de Eliminación')),
                ('codigo_reserva', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Código de Reserva')),
                ('fecha_servicio', models.DateField(db_index=True, verbose_name='Fecha del Servicio')),
                ('hora_servicio', models.TimeField(verbose_name='Hora del Servicio')),
                ('cantidad_pasajeros', models.PositiveIntegerField(verbose_name='N.° de Pasajeros')),
                ('origen', models.CharField(max_length=255, verbose_name='Punto de Recojo')),
                ('destino', models.CharField(max_length=255, verbose_name='Destino')),
                ('tarifa_final', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tarifa Final (S/)')),
                ('estado_reserva', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('EN_CURSO', 'En Curso'), ('COMPLETADA', 'Completada'), ('RECHAZADA', 'Rechazada'), ('CANCELADA', 'Cancelada')], db_index=True, default='PENDIENTE', max_length=15, verbose_name='Estado de la Reserva')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas Adicionales')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'reservas',
                'ordering': ['-fecha_servicio', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Fecha de Eliminación')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Servicio')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('tarifa_referencial', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tarifa Referencial (S/)')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='¿Servicio Activo?')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'servicios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Fecha de Eliminación')),
                ('placa', models.CharField(max_length=10, unique=True, verbose_name='Placa')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('capacidad', models.IntegerField(verbose_name='Capacidad (pasajeros)')),
                ('anio', models.IntegerField(verbose_name='Año de Fabricación')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_RUTA', 'En Ruta'), ('MANTENIMIENTO', 'En Mantenimiento')], db_index=True, default='DISPONIBLE', max_length=20, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'db_table': 'vehiculos',
                'ordering': ['placa'],
            },
        ),
    ]
