# Generated by Django 5.2.15 on 2026-06-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='estado_pago',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado')], default='PENDIENTE', max_length=15, verbose_name='Estado de Pago'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='metodo_pago_registro',
            field=models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('YAPE', 'Yape'), ('PLIN', 'Plin')], max_length=20, null=True, verbose_name='Método de Pago'),
        ),
    ]
