# Generated by Django 5.2.15 on 2026-06-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0004_mensajecontacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajecontacto',
            name='leido',
            field=models.BooleanField(default=False, verbose_name='Leído'),
        ),
    ]
