# Generated by Django 5.2.15 on 2026-07-01 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0005_mensajecontacto_leido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='cliente_correo',
            field=models.EmailField(default='sin@correo.com', max_length=254, verbose_name='Correo del Cliente'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='cliente_nombre',
            field=models.CharField(default='Cliente Web', max_length=200, verbose_name='Nombre del Cliente'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Admin (Creador)'),
        ),
    ]
