# Generated by Django 5.2.15 on 2026-07-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0006_reserva_cliente_correo_reserva_cliente_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='cliente_telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono del Cliente'),
        ),
    ]
