# Generated by Django 5.2.15 on 2026-07-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0007_reserva_cliente_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='detalles',
            field=models.TextField(blank=True, null=True, verbose_name='Detalles'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tipo_vehiculo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Vehículo'),
        ),
    ]
