# Generated by Django 5.2.15 on 2026-07-01 15:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0008_vehiculo_detalles_vehiculo_tipo_vehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='capacidad_carga',
            field=models.FloatField(default=0.0, verbose_name='Capacidad de Carga (kg)'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='kilometraje_actual',
            field=models.IntegerField(default=0, verbose_name='Kilometraje Actual'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='km_ultimo_mantenimiento',
            field=models.IntegerField(default=0, verbose_name='Km Último Mantenimiento'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(default='Desconocida', max_length=50, verbose_name='Marca'),
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Fecha de Eliminación')),
                ('kilometraje_realizado', models.IntegerField(verbose_name='Kilometraje al Mantenimiento')),
                ('fecha', models.DateField(verbose_name='Fecha de Mantenimiento')),
                ('descripcion', models.TextField(verbose_name='Descripción de Tareas')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo Total')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='operaciones.vehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'db_table': 'mantenimientos',
                'ordering': ['-fecha'],
            },
        ),
    ]
