# Generated by Django 5.2.15 on 2026-07-02 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0009_vehiculo_capacidad_carga_vehiculo_kilometraje_actual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductor',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('NO_DISPONIBLE', 'No Disponible')], db_index=True, default='DISPONIBLE', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('NO_DISPONIBLE', 'No Disponible'), ('MANTENIMIENTO', 'En Mantenimiento')], db_index=True, default='DISPONIBLE', max_length=20, verbose_name='Estado'),
        ),
    ]
