# Generated by Django 5.2.15 on 2026-07-02 03:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0010_alter_conductor_estado_alter_vehiculo_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-fecha_hora_inicio', '-created_at'], 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='fecha_servicio',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='hora_servicio',
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_hora_fin',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha y Hora de Fin'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_hora_inicio',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha y Hora de Inicio'),
        ),
    ]
