# Generated by Django 5.2.15 on 2026-07-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0011_alter_reserva_options_remove_reserva_fecha_servicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='frecuencia_mantenimiento_km',
            field=models.IntegerField(default=5000, verbose_name='Frecuencia de Mantenimiento (km)'),
        ),
    ]
