# Generated by Django 5.2.15 on 2026-07-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0012_add_frecuencia_mantenimiento_km'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='km_ultimo_mantenimiento',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='kilometraje_base',
            field=models.IntegerField(default=0, verbose_name='Kilometraje Base'),
        ),
    ]
