# Generated by Django 5.2.8 on 2026-07-08 11:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0013_remove_vehiculo_km_ultimo_mantenimiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroCombustible',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Fecha de Eliminación')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('odometro_actual', models.IntegerField(verbose_name='Odómetro Actual (km)')),
                ('cantidad_litros', models.FloatField(verbose_name='Cantidad (Litros)')),
                ('costo_total', models.FloatField(verbose_name='Costo Total')),
                ('tanque_lleno', models.BooleanField(default=False, verbose_name='Tanque Lleno')),
                ('consumo_calculado', models.FloatField(blank=True, null=True, verbose_name='Consumo Calculado (L/100km)')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_combustible', to='operaciones.vehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Registro de Combustible',
                'verbose_name_plural': 'Registros de Combustible',
                'db_table': 'registro_combustible',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
    ]
