# Generated by Django 5.2.8 on 2026-07-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0014_registrocombustible'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocombustible',
            name='precio_por_litro',
            field=models.FloatField(blank=True, null=True, verbose_name='Precio por Litro'),
        ),
    ]
