# Generated by Django 5.2.8 on 2026-07-08 11:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0015_registrocombustible_precio_por_litro'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanificacionViaje',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Fecha de Eliminación')),
                ('fecha_planificacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Planificación')),
                ('kilometraje_inicial', models.IntegerField(verbose_name='Kilometraje Inicial')),
                ('kilometraje_final', models.IntegerField(verbose_name='Kilometraje Final')),
                ('precio_galon', models.FloatField(verbose_name='Precio del Galón')),
                ('distancia', models.IntegerField(verbose_name='Distancia (km)')),
                ('litros_estimados', models.FloatField(verbose_name='Litros Estimados')),
                ('costo_estimado', models.FloatField(verbose_name='Costo Estimado')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planificaciones', to='operaciones.vehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Planificación de Viaje',
                'verbose_name_plural': 'Planificaciones de Viajes',
                'db_table': 'planificacion_viaje',
                'ordering': ['-fecha_planificacion'],
            },
        ),
    ]
